/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 71
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_PUSH = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_PUSH_LITERAL = 7,
  anon_sym_PEEK = 8,
  anon_sym_LBRACK = 9,
  aux_sym_peek_slice_token1 = 10,
  anon_sym_DOT_DOT = 11,
  anon_sym_RBRACK = 12,
  anon_sym_ANY = 13,
  anon_sym_DROP = 14,
  anon_sym_EOI = 15,
  anon_sym_NEWLINE = 16,
  anon_sym_PEEK_ALL = 17,
  anon_sym_POP = 18,
  anon_sym_POP_ALL = 19,
  anon_sym_SOI = 20,
  sym_const = 21,
  aux_sym_identifier_token1 = 22,
  anon_sym__ = 23,
  anon_sym_AT = 24,
  anon_sym_DOLLAR = 25,
  anon_sym_BANG = 26,
  anon_sym_PIPE = 27,
  sym_character = 28,
  anon_sym_DQUOTE = 29,
  sym__unescaped_double_string_fragment = 30,
  sym__escape_sequence = 31,
  anon_sym_CARET = 32,
  anon_sym_POUND = 33,
  anon_sym_TILDE = 34,
  anon_sym_AMP = 35,
  anon_sym_QMARK = 36,
  anon_sym_STAR = 37,
  anon_sym_PLUS = 38,
  aux_sym_postfix_operator_token1 = 39,
  anon_sym_COMMA = 40,
  sym_line_comment = 41,
  anon_sym_SLASH_STAR = 42,
  aux_sym_block_comment_token1 = 43,
  anon_sym_SLASH = 44,
  sym_pest = 45,
  sym_grammar_rule = 46,
  sym_push = 47,
  sym_push_literal = 48,
  sym_peek_slice = 49,
  sym_builtin = 50,
  sym_identifier = 51,
  sym_modifier = 52,
  sym_expression = 53,
  sym_term = 54,
  sym__node = 55,
  sym__terminal = 56,
  sym_range = 57,
  sym_string = 58,
  sym_insensitive_string = 59,
  sym_node_tag = 60,
  sym_tag_id = 61,
  sym_infix_operator = 62,
  sym_prefix_operator = 63,
  sym_postfix_operator = 64,
  sym_block_comment = 65,
  aux_sym_pest_repeat1 = 66,
  aux_sym_expression_repeat1 = 67,
  aux_sym_term_repeat1 = 68,
  aux_sym_term_repeat2 = 69,
  aux_sym_string_repeat1 = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PUSH] = "PUSH",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PUSH_LITERAL] = "PUSH_LITERAL",
  [anon_sym_PEEK] = "PEEK",
  [anon_sym_LBRACK] = "[",
  [aux_sym_peek_slice_token1] = "peek_slice_token1",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_RBRACK] = "]",
  [anon_sym_ANY] = "ANY",
  [anon_sym_DROP] = "DROP",
  [anon_sym_EOI] = "EOI",
  [anon_sym_NEWLINE] = "NEWLINE",
  [anon_sym_PEEK_ALL] = "PEEK_ALL",
  [anon_sym_POP] = "POP",
  [anon_sym_POP_ALL] = "POP_ALL",
  [anon_sym_SOI] = "SOI",
  [sym_const] = "const",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym__] = "_",
  [anon_sym_AT] = "@",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_BANG] = "!",
  [anon_sym_PIPE] = "|",
  [sym_character] = "character",
  [anon_sym_DQUOTE] = "\"",
  [sym__unescaped_double_string_fragment] = "_unescaped_double_string_fragment",
  [sym__escape_sequence] = "_escape_sequence",
  [anon_sym_CARET] = "^",
  [anon_sym_POUND] = "#",
  [anon_sym_TILDE] = "~",
  [anon_sym_AMP] = "&",
  [anon_sym_QMARK] = "\?",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [aux_sym_postfix_operator_token1] = "postfix_operator_token1",
  [anon_sym_COMMA] = ",",
  [sym_line_comment] = "line_comment",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [anon_sym_SLASH] = "/",
  [sym_pest] = "pest",
  [sym_grammar_rule] = "grammar_rule",
  [sym_push] = "push",
  [sym_push_literal] = "push_literal",
  [sym_peek_slice] = "peek_slice",
  [sym_builtin] = "builtin",
  [sym_identifier] = "identifier",
  [sym_modifier] = "modifier",
  [sym_expression] = "expression",
  [sym_term] = "term",
  [sym__node] = "_node",
  [sym__terminal] = "_terminal",
  [sym_range] = "range",
  [sym_string] = "string",
  [sym_insensitive_string] = "insensitive_string",
  [sym_node_tag] = "node_tag",
  [sym_tag_id] = "tag_id",
  [sym_infix_operator] = "infix_operator",
  [sym_prefix_operator] = "prefix_operator",
  [sym_postfix_operator] = "postfix_operator",
  [sym_block_comment] = "block_comment",
  [aux_sym_pest_repeat1] = "pest_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_term_repeat2] = "term_repeat2",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PUSH] = anon_sym_PUSH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PUSH_LITERAL] = anon_sym_PUSH_LITERAL,
  [anon_sym_PEEK] = anon_sym_PEEK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_peek_slice_token1] = aux_sym_peek_slice_token1,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_ANY] = anon_sym_ANY,
  [anon_sym_DROP] = anon_sym_DROP,
  [anon_sym_EOI] = anon_sym_EOI,
  [anon_sym_NEWLINE] = anon_sym_NEWLINE,
  [anon_sym_PEEK_ALL] = anon_sym_PEEK_ALL,
  [anon_sym_POP] = anon_sym_POP,
  [anon_sym_POP_ALL] = anon_sym_POP_ALL,
  [anon_sym_SOI] = anon_sym_SOI,
  [sym_const] = sym_const,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym__] = anon_sym__,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_character] = sym_character,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__unescaped_double_string_fragment] = sym__unescaped_double_string_fragment,
  [sym__escape_sequence] = sym__escape_sequence,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_postfix_operator_token1] = aux_sym_postfix_operator_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_pest] = sym_pest,
  [sym_grammar_rule] = sym_grammar_rule,
  [sym_push] = sym_push,
  [sym_push_literal] = sym_push_literal,
  [sym_peek_slice] = sym_peek_slice,
  [sym_builtin] = sym_builtin,
  [sym_identifier] = sym_identifier,
  [sym_modifier] = sym_modifier,
  [sym_expression] = sym_expression,
  [sym_term] = sym_term,
  [sym__node] = sym__node,
  [sym__terminal] = sym__terminal,
  [sym_range] = sym_range,
  [sym_string] = sym_string,
  [sym_insensitive_string] = sym_insensitive_string,
  [sym_node_tag] = sym_node_tag,
  [sym_tag_id] = sym_tag_id,
  [sym_infix_operator] = sym_infix_operator,
  [sym_prefix_operator] = sym_prefix_operator,
  [sym_postfix_operator] = sym_postfix_operator,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_pest_repeat1] = aux_sym_pest_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_term_repeat2] = aux_sym_term_repeat2,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUSH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUSH_LITERAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PEEK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_peek_slice_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ANY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DROP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EOI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NEWLINE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PEEK_ALL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POP_ALL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SOI] = {
    .visible = true,
    .named = false,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__unescaped_double_string_fragment] = {
    .visible = false,
    .named = true,
  },
  [sym__escape_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_postfix_operator_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_pest] = {
    .visible = true,
    .named = true,
  },
  [sym_grammar_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_push] = {
    .visible = true,
    .named = true,
  },
  [sym_push_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_peek_slice] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__terminal] = {
    .visible = false,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_insensitive_string] = {
    .visible = true,
    .named = true,
  },
  [sym_node_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_id] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_postfix_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pest_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '!', 91,
        '"', 94,
        '#', 101,
        '$', 90,
        '&', 103,
        '\'', 6,
        '(', 35,
        ')', 36,
        '*', 105,
        '+', 107,
        ',', 109,
        '-', 19,
        '.', 11,
        '/', 118,
        '=', 31,
        '?', 104,
        '@', 89,
        'A', 72,
        'D', 79,
        'E', 74,
        'N', 54,
        'P', 58,
        'S', 75,
        '[', 39,
        '\\', 13,
        ']', 42,
        '^', 100,
        '_', 88,
        '{', 32,
        '|', 92,
        '}', 33,
        '~', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 91,
        '"', 94,
        '#', 101,
        '&', 103,
        '\'', 6,
        '(', 35,
        '.', 11,
        '/', 7,
        'A', 72,
        'D', 79,
        'E', 74,
        'N', 54,
        'P', 58,
        'S', 75,
        ']', 42,
        '^', 100,
        '|', 92,
        '+', 19,
        '-', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(91);
      if (lookahead == '$') ADVANCE(90);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '@') ADVANCE(89);
      if (lookahead == '_') ADVANCE(87);
      if (lookahead == '{') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead == '/') ADVANCE(95);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(93);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(93);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(115);
      if (lookahead == '/') ADVANCE(113);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(117);
      if (lookahead == '/') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(117);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(116);
      if (lookahead == '/') ADVANCE(111);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(25);
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(26);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == '{') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == '{') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == '}') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '}') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(99);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '!', 91,
        '"', 94,
        '#', 101,
        '$', 90,
        '&', 103,
        '\'', 6,
        '(', 35,
        ')', 36,
        '*', 105,
        '+', 107,
        ',', 109,
        '-', 19,
        '.', 11,
        '/', 118,
        '=', 31,
        '?', 104,
        '@', 89,
        'A', 72,
        'D', 79,
        'E', 74,
        'N', 54,
        'P', 58,
        'S', 75,
        '[', 39,
        ']', 42,
        '^', 100,
        '_', 88,
        '{', 32,
        '|', 92,
        '}', 33,
        '~', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        ')', 36,
        '*', 105,
        '+', 106,
        ',', 109,
        '/', 7,
        '=', 31,
        '?', 104,
        '[', 39,
        '{', 32,
        '|', 92,
        '}', 33,
        '~', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PUSH);
      if (lookahead == '_') ADVANCE(70);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PUSH_LITERAL);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PEEK);
      if (lookahead == '_') ADVANCE(53);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_peek_slice_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_ANY);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DROP);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EOI);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_NEWLINE);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PEEK_ALL);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_POP);
      if (lookahead == '_') ADVANCE(51);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(85);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_POP_ALL);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SOI);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'A') ADVANCE(69);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'A') ADVANCE(67);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'A') ADVANCE(71);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'E') ADVANCE(83);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'E') ADVANCE(64);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'E') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'E') ADVANCE(80);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'O') ADVANCE(77);
      if (lookahead == 'U') ADVANCE(81);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'H') ADVANCE(34);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'I') ADVANCE(45);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'I') ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'I') ADVANCE(82);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'I') ADVANCE(73);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'K') ADVANCE(38);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(49);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(63);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(65);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(62);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'L') ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'N') ADVANCE(84);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'N') ADVANCE(56);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'O') ADVANCE(60);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'O') ADVANCE(61);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'O') ADVANCE(78);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'P') ADVANCE(48);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'P') ADVANCE(44);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'R') ADVANCE(76);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'R') ADVANCE(52);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'S') ADVANCE(59);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'T') ADVANCE(57);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'W') ADVANCE(68);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == 'Y') ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_const);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym__);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym__unescaped_double_string_fragment);
      if (lookahead == '*') ADVANCE(98);
      if (lookahead == '/') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym__unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(95);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym__unescaped_double_string_fragment);
      if (lookahead == '!' ||
          lookahead == '/') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '!' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym__unescaped_double_string_fragment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__escape_sequence);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_postfix_operator_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(110);
      if (lookahead == '/') ADVANCE(114);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(110);
      if (lookahead == '!' ||
          lookahead == '/') ADVANCE(112);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(110);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '!' ||
          lookahead == '/') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(9);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '*') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(9);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(115);
      if (lookahead == '/') ADVANCE(113);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 29},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 29},
  [23] = {.lex_state = 29},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 29},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 29},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 29},
  [37] = {.lex_state = 29},
  [38] = {.lex_state = 29},
  [39] = {.lex_state = 29},
  [40] = {.lex_state = 29},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 29},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 29},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 29},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 29},
  [57] = {.lex_state = 29},
  [58] = {.lex_state = 29},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 29},
  [63] = {.lex_state = 29},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 8},
  [72] = {.lex_state = 29},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_block_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PUSH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PUSH_LITERAL] = ACTIONS(1),
    [anon_sym_PEEK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_peek_slice_token1] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_ANY] = ACTIONS(1),
    [anon_sym_DROP] = ACTIONS(1),
    [anon_sym_EOI] = ACTIONS(1),
    [anon_sym_NEWLINE] = ACTIONS(1),
    [anon_sym_PEEK_ALL] = ACTIONS(1),
    [anon_sym_POP] = ACTIONS(1),
    [anon_sym_POP_ALL] = ACTIONS(1),
    [anon_sym_SOI] = ACTIONS(1),
    [sym_const] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_character] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__escape_sequence] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [aux_sym_postfix_operator_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_pest] = STATE(74),
    [sym_grammar_rule] = STATE(56),
    [sym_identifier] = STATE(84),
    [sym_block_comment] = STATE(1),
    [aux_sym_pest_repeat1] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_const] = ACTIONS(9),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_push] = STATE(36),
    [sym_push_literal] = STATE(36),
    [sym_peek_slice] = STATE(36),
    [sym_builtin] = STATE(36),
    [sym_identifier] = STATE(36),
    [sym_expression] = STATE(90),
    [sym_term] = STATE(43),
    [sym__node] = STATE(16),
    [sym__terminal] = STATE(27),
    [sym_range] = STATE(36),
    [sym_string] = STATE(36),
    [sym_insensitive_string] = STATE(36),
    [sym_node_tag] = STATE(8),
    [sym_prefix_operator] = STATE(14),
    [sym_block_comment] = STATE(2),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PUSH] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_PUSH_LITERAL] = ACTIONS(17),
    [anon_sym_PEEK] = ACTIONS(19),
    [anon_sym_ANY] = ACTIONS(21),
    [anon_sym_DROP] = ACTIONS(21),
    [anon_sym_EOI] = ACTIONS(21),
    [anon_sym_NEWLINE] = ACTIONS(21),
    [anon_sym_PEEK_ALL] = ACTIONS(21),
    [anon_sym_POP] = ACTIONS(21),
    [anon_sym_POP_ALL] = ACTIONS(21),
    [anon_sym_SOI] = ACTIONS(21),
    [sym_const] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_PIPE] = ACTIONS(27),
    [sym_character] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym_push] = STATE(36),
    [sym_push_literal] = STATE(36),
    [sym_peek_slice] = STATE(36),
    [sym_builtin] = STATE(36),
    [sym_identifier] = STATE(36),
    [sym_expression] = STATE(69),
    [sym_term] = STATE(43),
    [sym__node] = STATE(16),
    [sym__terminal] = STATE(27),
    [sym_range] = STATE(36),
    [sym_string] = STATE(36),
    [sym_insensitive_string] = STATE(36),
    [sym_node_tag] = STATE(8),
    [sym_prefix_operator] = STATE(14),
    [sym_block_comment] = STATE(3),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PUSH] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_PUSH_LITERAL] = ACTIONS(17),
    [anon_sym_PEEK] = ACTIONS(19),
    [anon_sym_ANY] = ACTIONS(21),
    [anon_sym_DROP] = ACTIONS(21),
    [anon_sym_EOI] = ACTIONS(21),
    [anon_sym_NEWLINE] = ACTIONS(21),
    [anon_sym_PEEK_ALL] = ACTIONS(21),
    [anon_sym_POP] = ACTIONS(21),
    [anon_sym_POP_ALL] = ACTIONS(21),
    [anon_sym_SOI] = ACTIONS(21),
    [sym_const] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_PIPE] = ACTIONS(27),
    [sym_character] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(4)] = {
    [sym_push] = STATE(36),
    [sym_push_literal] = STATE(36),
    [sym_peek_slice] = STATE(36),
    [sym_builtin] = STATE(36),
    [sym_identifier] = STATE(36),
    [sym_expression] = STATE(76),
    [sym_term] = STATE(43),
    [sym__node] = STATE(16),
    [sym__terminal] = STATE(27),
    [sym_range] = STATE(36),
    [sym_string] = STATE(36),
    [sym_insensitive_string] = STATE(36),
    [sym_node_tag] = STATE(8),
    [sym_prefix_operator] = STATE(14),
    [sym_block_comment] = STATE(4),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PUSH] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_PUSH_LITERAL] = ACTIONS(17),
    [anon_sym_PEEK] = ACTIONS(19),
    [anon_sym_ANY] = ACTIONS(21),
    [anon_sym_DROP] = ACTIONS(21),
    [anon_sym_EOI] = ACTIONS(21),
    [anon_sym_NEWLINE] = ACTIONS(21),
    [anon_sym_PEEK_ALL] = ACTIONS(21),
    [anon_sym_POP] = ACTIONS(21),
    [anon_sym_POP_ALL] = ACTIONS(21),
    [anon_sym_SOI] = ACTIONS(21),
    [sym_const] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_PIPE] = ACTIONS(27),
    [sym_character] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(5)] = {
    [sym_push] = STATE(36),
    [sym_push_literal] = STATE(36),
    [sym_peek_slice] = STATE(36),
    [sym_builtin] = STATE(36),
    [sym_identifier] = STATE(36),
    [sym_expression] = STATE(77),
    [sym_term] = STATE(43),
    [sym__node] = STATE(16),
    [sym__terminal] = STATE(27),
    [sym_range] = STATE(36),
    [sym_string] = STATE(36),
    [sym_insensitive_string] = STATE(36),
    [sym_node_tag] = STATE(8),
    [sym_prefix_operator] = STATE(14),
    [sym_block_comment] = STATE(5),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PUSH] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_PUSH_LITERAL] = ACTIONS(17),
    [anon_sym_PEEK] = ACTIONS(19),
    [anon_sym_ANY] = ACTIONS(21),
    [anon_sym_DROP] = ACTIONS(21),
    [anon_sym_EOI] = ACTIONS(21),
    [anon_sym_NEWLINE] = ACTIONS(21),
    [anon_sym_PEEK_ALL] = ACTIONS(21),
    [anon_sym_POP] = ACTIONS(21),
    [anon_sym_POP_ALL] = ACTIONS(21),
    [anon_sym_SOI] = ACTIONS(21),
    [sym_const] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_PIPE] = ACTIONS(27),
    [sym_character] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(6)] = {
    [sym_push] = STATE(36),
    [sym_push_literal] = STATE(36),
    [sym_peek_slice] = STATE(36),
    [sym_builtin] = STATE(36),
    [sym_identifier] = STATE(36),
    [sym_term] = STATE(49),
    [sym__node] = STATE(16),
    [sym__terminal] = STATE(27),
    [sym_range] = STATE(36),
    [sym_string] = STATE(36),
    [sym_insensitive_string] = STATE(36),
    [sym_node_tag] = STATE(8),
    [sym_prefix_operator] = STATE(14),
    [sym_block_comment] = STATE(6),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PUSH] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_PUSH_LITERAL] = ACTIONS(17),
    [anon_sym_PEEK] = ACTIONS(19),
    [anon_sym_ANY] = ACTIONS(21),
    [anon_sym_DROP] = ACTIONS(21),
    [anon_sym_EOI] = ACTIONS(21),
    [anon_sym_NEWLINE] = ACTIONS(21),
    [anon_sym_PEEK_ALL] = ACTIONS(21),
    [anon_sym_POP] = ACTIONS(21),
    [anon_sym_POP_ALL] = ACTIONS(21),
    [anon_sym_SOI] = ACTIONS(21),
    [sym_const] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(25),
    [sym_character] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(7)] = {
    [sym_push] = STATE(36),
    [sym_push_literal] = STATE(36),
    [sym_peek_slice] = STATE(36),
    [sym_builtin] = STATE(36),
    [sym_identifier] = STATE(36),
    [sym_term] = STATE(52),
    [sym__node] = STATE(16),
    [sym__terminal] = STATE(27),
    [sym_range] = STATE(36),
    [sym_string] = STATE(36),
    [sym_insensitive_string] = STATE(36),
    [sym_node_tag] = STATE(8),
    [sym_prefix_operator] = STATE(14),
    [sym_block_comment] = STATE(7),
    [aux_sym_term_repeat1] = STATE(9),
    [anon_sym_PUSH] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_PUSH_LITERAL] = ACTIONS(17),
    [anon_sym_PEEK] = ACTIONS(19),
    [anon_sym_ANY] = ACTIONS(21),
    [anon_sym_DROP] = ACTIONS(21),
    [anon_sym_EOI] = ACTIONS(21),
    [anon_sym_NEWLINE] = ACTIONS(21),
    [anon_sym_PEEK_ALL] = ACTIONS(21),
    [anon_sym_POP] = ACTIONS(21),
    [anon_sym_POP_ALL] = ACTIONS(21),
    [anon_sym_SOI] = ACTIONS(21),
    [sym_const] = ACTIONS(23),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(25),
    [sym_character] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_CARET] = ACTIONS(33),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_AMP] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(13), 1,
      anon_sym_PUSH,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_PUSH_LITERAL,
    ACTIONS(19), 1,
      anon_sym_PEEK,
    ACTIONS(23), 1,
      sym_const,
    ACTIONS(29), 1,
      sym_character,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_CARET,
    STATE(8), 1,
      sym_block_comment,
    STATE(10), 1,
      aux_sym_term_repeat1,
    STATE(14), 1,
      sym_prefix_operator,
    STATE(21), 1,
      sym__node,
    STATE(27), 1,
      sym__terminal,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_AMP,
    ACTIONS(21), 8,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
    STATE(36), 8,
      sym_push,
      sym_push_literal,
      sym_peek_slice,
      sym_builtin,
      sym_identifier,
      sym_range,
      sym_string,
      sym_insensitive_string,
  [73] = 19,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(13), 1,
      anon_sym_PUSH,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_PUSH_LITERAL,
    ACTIONS(19), 1,
      anon_sym_PEEK,
    ACTIONS(23), 1,
      sym_const,
    ACTIONS(29), 1,
      sym_character,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_CARET,
    STATE(9), 1,
      sym_block_comment,
    STATE(11), 1,
      aux_sym_term_repeat1,
    STATE(14), 1,
      sym_prefix_operator,
    STATE(21), 1,
      sym__node,
    STATE(27), 1,
      sym__terminal,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_AMP,
    ACTIONS(21), 8,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
    STATE(36), 8,
      sym_push,
      sym_push_literal,
      sym_peek_slice,
      sym_builtin,
      sym_identifier,
      sym_range,
      sym_string,
      sym_insensitive_string,
  [146] = 19,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(13), 1,
      anon_sym_PUSH,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_PUSH_LITERAL,
    ACTIONS(19), 1,
      anon_sym_PEEK,
    ACTIONS(23), 1,
      sym_const,
    ACTIONS(29), 1,
      sym_character,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_CARET,
    STATE(10), 1,
      sym_block_comment,
    STATE(11), 1,
      aux_sym_term_repeat1,
    STATE(14), 1,
      sym_prefix_operator,
    STATE(20), 1,
      sym__node,
    STATE(27), 1,
      sym__terminal,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_AMP,
    ACTIONS(21), 8,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
    STATE(36), 8,
      sym_push,
      sym_push_literal,
      sym_peek_slice,
      sym_builtin,
      sym_identifier,
      sym_range,
      sym_string,
      sym_insensitive_string,
  [219] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_prefix_operator,
    ACTIONS(41), 2,
      anon_sym_BANG,
      anon_sym_AMP,
    STATE(11), 2,
      sym_block_comment,
      aux_sym_term_repeat1,
    ACTIONS(39), 4,
      anon_sym_LPAREN,
      sym_character,
      anon_sym_DQUOTE,
      anon_sym_CARET,
    ACTIONS(37), 13,
      anon_sym_PUSH,
      anon_sym_PUSH_LITERAL,
      anon_sym_PEEK,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
      sym_const,
      aux_sym_identifier_token1,
  [258] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_block_comment,
    ACTIONS(46), 7,
      anon_sym_LPAREN,
      anon_sym_BANG,
      sym_character,
      anon_sym_DQUOTE,
      anon_sym_CARET,
      anon_sym_POUND,
      anon_sym_AMP,
    ACTIONS(44), 13,
      anon_sym_PUSH,
      anon_sym_PUSH_LITERAL,
      anon_sym_PEEK,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
      sym_const,
      aux_sym_identifier_token1,
  [292] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_block_comment,
    ACTIONS(50), 6,
      anon_sym_LPAREN,
      anon_sym_BANG,
      sym_character,
      anon_sym_DQUOTE,
      anon_sym_CARET,
      anon_sym_AMP,
    ACTIONS(48), 13,
      anon_sym_PUSH,
      anon_sym_PUSH_LITERAL,
      anon_sym_PEEK,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
      sym_const,
      aux_sym_identifier_token1,
  [325] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_block_comment,
    ACTIONS(54), 6,
      anon_sym_LPAREN,
      anon_sym_BANG,
      sym_character,
      anon_sym_DQUOTE,
      anon_sym_CARET,
      anon_sym_AMP,
    ACTIONS(52), 13,
      anon_sym_PUSH,
      anon_sym_PUSH_LITERAL,
      anon_sym_PEEK,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
      sym_const,
      aux_sym_identifier_token1,
  [358] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_block_comment,
    ACTIONS(58), 6,
      anon_sym_LPAREN,
      anon_sym_BANG,
      sym_character,
      anon_sym_DQUOTE,
      anon_sym_CARET,
      anon_sym_AMP,
    ACTIONS(56), 13,
      anon_sym_PUSH,
      anon_sym_PUSH_LITERAL,
      anon_sym_PEEK,
      anon_sym_ANY,
      anon_sym_DROP,
      anon_sym_EOI,
      anon_sym_NEWLINE,
      anon_sym_PEEK_ALL,
      anon_sym_POP,
      anon_sym_POP_ALL,
      anon_sym_SOI,
      sym_const,
      aux_sym_identifier_token1,
  [391] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_block_comment,
    STATE(17), 1,
      aux_sym_term_repeat2,
    STATE(31), 1,
      sym_postfix_operator,
    ACTIONS(64), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(62), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [421] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block_comment,
    STATE(18), 1,
      aux_sym_term_repeat2,
    STATE(31), 1,
      sym_postfix_operator,
    ACTIONS(64), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(66), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [451] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_postfix_operator,
    STATE(18), 2,
      sym_block_comment,
      aux_sym_term_repeat2,
    ACTIONS(73), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(71), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [479] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      aux_sym_term_repeat2,
    STATE(19), 1,
      sym_block_comment,
    STATE(31), 1,
      sym_postfix_operator,
    ACTIONS(64), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(76), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [509] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block_comment,
    STATE(22), 1,
      aux_sym_term_repeat2,
    STATE(31), 1,
      sym_postfix_operator,
    ACTIONS(64), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(76), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [539] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      aux_sym_term_repeat2,
    STATE(21), 1,
      sym_block_comment,
    STATE(31), 1,
      sym_postfix_operator,
    ACTIONS(64), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(66), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [569] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      aux_sym_term_repeat2,
    STATE(22), 1,
      sym_block_comment,
    STATE(31), 1,
      sym_postfix_operator,
    ACTIONS(64), 3,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(78), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [599] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_block_comment,
    ACTIONS(80), 9,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [620] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(24), 1,
      sym_block_comment,
    ACTIONS(82), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [643] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_block_comment,
    ACTIONS(86), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [663] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_block_comment,
    ACTIONS(88), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [683] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_block_comment,
    ACTIONS(90), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [703] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_block_comment,
    ACTIONS(92), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [723] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_block_comment,
    ACTIONS(94), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [743] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_block_comment,
    ACTIONS(96), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [763] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_block_comment,
    ACTIONS(98), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [783] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_block_comment,
    ACTIONS(82), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [803] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_block_comment,
    ACTIONS(100), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [823] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_block_comment,
    ACTIONS(102), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [843] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_block_comment,
    ACTIONS(104), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [863] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_block_comment,
    ACTIONS(106), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [883] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_block_comment,
    ACTIONS(108), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [903] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_block_comment,
    ACTIONS(110), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [923] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_block_comment,
    ACTIONS(112), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [943] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_block_comment,
    ACTIONS(114), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [963] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_block_comment,
    ACTIONS(116), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [983] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_block_comment,
    ACTIONS(118), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_QMARK,
      anon_sym_STAR,
      anon_sym_PLUS,
  [1003] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_infix_operator,
    STATE(43), 1,
      sym_block_comment,
    STATE(50), 1,
      aux_sym_expression_repeat1,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(122), 2,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [1027] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block_comment,
    STATE(86), 1,
      sym_modifier,
    ACTIONS(126), 4,
      anon_sym__,
      anon_sym_AT,
      anon_sym_DOLLAR,
      anon_sym_BANG,
  [1049] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_infix_operator,
    STATE(45), 1,
      sym_block_comment,
    STATE(47), 1,
      aux_sym_expression_repeat1,
    ACTIONS(122), 2,
      anon_sym_PIPE,
      anon_sym_TILDE,
    ACTIONS(128), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1073] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      sym_const,
    ACTIONS(135), 1,
      aux_sym_identifier_token1,
    STATE(56), 1,
      sym_grammar_rule,
    STATE(84), 1,
      sym_identifier,
    STATE(46), 2,
      sym_block_comment,
      aux_sym_pest_repeat1,
  [1099] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_infix_operator,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(140), 2,
      anon_sym_PIPE,
      anon_sym_TILDE,
    STATE(47), 2,
      sym_block_comment,
      aux_sym_expression_repeat1,
  [1121] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_const,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    STATE(46), 1,
      aux_sym_pest_repeat1,
    STATE(48), 1,
      sym_block_comment,
    STATE(56), 1,
      sym_grammar_rule,
    STATE(84), 1,
      sym_identifier,
  [1149] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_infix_operator,
    STATE(45), 1,
      aux_sym_expression_repeat1,
    STATE(49), 1,
      sym_block_comment,
    ACTIONS(122), 2,
      anon_sym_PIPE,
      anon_sym_TILDE,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1173] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_infix_operator,
    STATE(47), 1,
      aux_sym_expression_repeat1,
    STATE(50), 1,
      sym_block_comment,
    ACTIONS(122), 2,
      anon_sym_PIPE,
      anon_sym_TILDE,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1197] = 6,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    ACTIONS(151), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      anon_sym_SLASH_STAR,
    STATE(51), 1,
      sym_block_comment,
    STATE(53), 1,
      aux_sym_string_repeat1,
    ACTIONS(149), 2,
      sym__unescaped_double_string_fragment,
      sym__escape_sequence,
  [1217] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 1,
      sym_block_comment,
    ACTIONS(138), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_TILDE,
  [1233] = 5,
    ACTIONS(151), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 2,
      sym__unescaped_double_string_fragment,
      sym__escape_sequence,
    STATE(53), 2,
      sym_block_comment,
      aux_sym_string_repeat1,
  [1251] = 6,
    ACTIONS(151), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(160), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      aux_sym_string_repeat1,
    STATE(54), 1,
      sym_block_comment,
    ACTIONS(149), 2,
      sym__unescaped_double_string_fragment,
      sym__escape_sequence,
  [1271] = 5,
    ACTIONS(151), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_block_comment,
    ACTIONS(164), 2,
      sym__unescaped_double_string_fragment,
      sym__escape_sequence,
  [1288] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_block_comment,
    ACTIONS(168), 2,
      sym_const,
      aux_sym_identifier_token1,
  [1305] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
    STATE(57), 1,
      sym_block_comment,
    ACTIONS(172), 2,
      sym_const,
      aux_sym_identifier_token1,
  [1322] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    STATE(58), 1,
      sym_block_comment,
    ACTIONS(176), 2,
      sym_const,
      aux_sym_identifier_token1,
  [1339] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(178), 1,
      aux_sym_peek_slice_token1,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
    STATE(59), 1,
      sym_block_comment,
  [1355] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      sym_block_comment,
  [1371] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(186), 1,
      aux_sym_peek_slice_token1,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    STATE(61), 1,
      sym_block_comment,
  [1387] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      aux_sym_postfix_operator_token1,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      sym_block_comment,
  [1403] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(196), 1,
      aux_sym_postfix_operator_token1,
    STATE(63), 1,
      sym_block_comment,
  [1419] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      sym_block_comment,
    STATE(80), 1,
      sym_string,
  [1435] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(198), 1,
      aux_sym_peek_slice_token1,
    ACTIONS(200), 1,
      anon_sym_DOT_DOT,
    STATE(65), 1,
      sym_block_comment,
  [1451] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_string,
    STATE(66), 1,
      sym_block_comment,
  [1467] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(202), 1,
      aux_sym_identifier_token1,
    STATE(67), 1,
      sym_block_comment,
    STATE(82), 1,
      sym_tag_id,
  [1483] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      sym_block_comment,
  [1496] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_block_comment,
  [1509] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(208), 1,
      anon_sym_SLASH,
    STATE(70), 1,
      sym_block_comment,
  [1522] = 4,
    ACTIONS(151), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(210), 1,
      aux_sym_block_comment_token1,
    STATE(71), 1,
      sym_block_comment,
  [1535] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(212), 1,
      aux_sym_postfix_operator_token1,
    STATE(72), 1,
      sym_block_comment,
  [1548] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_block_comment,
  [1561] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      sym_block_comment,
  [1574] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      anon_sym_DOT_DOT,
    STATE(75), 1,
      sym_block_comment,
  [1587] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      sym_block_comment,
  [1600] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym_block_comment,
  [1613] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(224), 1,
      anon_sym_EQ,
    STATE(78), 1,
      sym_block_comment,
  [1626] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      sym_block_comment,
  [1639] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_block_comment,
  [1652] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(228), 1,
      anon_sym_DOT_DOT,
    STATE(81), 1,
      sym_block_comment,
  [1665] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(230), 1,
      anon_sym_EQ,
    STATE(82), 1,
      sym_block_comment,
  [1678] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_block_comment,
  [1691] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(232), 1,
      anon_sym_EQ,
    STATE(84), 1,
      sym_block_comment,
  [1704] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(85), 1,
      sym_block_comment,
  [1717] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(236), 1,
      anon_sym_LBRACE,
    STATE(86), 1,
      sym_block_comment,
  [1730] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    STATE(87), 1,
      sym_block_comment,
  [1743] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(240), 1,
      sym_character,
    STATE(88), 1,
      sym_block_comment,
  [1756] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    STATE(89), 1,
      sym_block_comment,
  [1769] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_block_comment,
  [1782] = 1,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 73,
  [SMALL_STATE(10)] = 146,
  [SMALL_STATE(11)] = 219,
  [SMALL_STATE(12)] = 258,
  [SMALL_STATE(13)] = 292,
  [SMALL_STATE(14)] = 325,
  [SMALL_STATE(15)] = 358,
  [SMALL_STATE(16)] = 391,
  [SMALL_STATE(17)] = 421,
  [SMALL_STATE(18)] = 451,
  [SMALL_STATE(19)] = 479,
  [SMALL_STATE(20)] = 509,
  [SMALL_STATE(21)] = 539,
  [SMALL_STATE(22)] = 569,
  [SMALL_STATE(23)] = 599,
  [SMALL_STATE(24)] = 620,
  [SMALL_STATE(25)] = 643,
  [SMALL_STATE(26)] = 663,
  [SMALL_STATE(27)] = 683,
  [SMALL_STATE(28)] = 703,
  [SMALL_STATE(29)] = 723,
  [SMALL_STATE(30)] = 743,
  [SMALL_STATE(31)] = 763,
  [SMALL_STATE(32)] = 783,
  [SMALL_STATE(33)] = 803,
  [SMALL_STATE(34)] = 823,
  [SMALL_STATE(35)] = 843,
  [SMALL_STATE(36)] = 863,
  [SMALL_STATE(37)] = 883,
  [SMALL_STATE(38)] = 903,
  [SMALL_STATE(39)] = 923,
  [SMALL_STATE(40)] = 943,
  [SMALL_STATE(41)] = 963,
  [SMALL_STATE(42)] = 983,
  [SMALL_STATE(43)] = 1003,
  [SMALL_STATE(44)] = 1027,
  [SMALL_STATE(45)] = 1049,
  [SMALL_STATE(46)] = 1073,
  [SMALL_STATE(47)] = 1099,
  [SMALL_STATE(48)] = 1121,
  [SMALL_STATE(49)] = 1149,
  [SMALL_STATE(50)] = 1173,
  [SMALL_STATE(51)] = 1197,
  [SMALL_STATE(52)] = 1217,
  [SMALL_STATE(53)] = 1233,
  [SMALL_STATE(54)] = 1251,
  [SMALL_STATE(55)] = 1271,
  [SMALL_STATE(56)] = 1288,
  [SMALL_STATE(57)] = 1305,
  [SMALL_STATE(58)] = 1322,
  [SMALL_STATE(59)] = 1339,
  [SMALL_STATE(60)] = 1355,
  [SMALL_STATE(61)] = 1371,
  [SMALL_STATE(62)] = 1387,
  [SMALL_STATE(63)] = 1403,
  [SMALL_STATE(64)] = 1419,
  [SMALL_STATE(65)] = 1435,
  [SMALL_STATE(66)] = 1451,
  [SMALL_STATE(67)] = 1467,
  [SMALL_STATE(68)] = 1483,
  [SMALL_STATE(69)] = 1496,
  [SMALL_STATE(70)] = 1509,
  [SMALL_STATE(71)] = 1522,
  [SMALL_STATE(72)] = 1535,
  [SMALL_STATE(73)] = 1548,
  [SMALL_STATE(74)] = 1561,
  [SMALL_STATE(75)] = 1574,
  [SMALL_STATE(76)] = 1587,
  [SMALL_STATE(77)] = 1600,
  [SMALL_STATE(78)] = 1613,
  [SMALL_STATE(79)] = 1626,
  [SMALL_STATE(80)] = 1639,
  [SMALL_STATE(81)] = 1652,
  [SMALL_STATE(82)] = 1665,
  [SMALL_STATE(83)] = 1678,
  [SMALL_STATE(84)] = 1691,
  [SMALL_STATE(85)] = 1704,
  [SMALL_STATE(86)] = 1717,
  [SMALL_STATE(87)] = 1730,
  [SMALL_STATE(88)] = 1743,
  [SMALL_STATE(89)] = 1756,
  [SMALL_STATE(90)] = 1769,
  [SMALL_STATE(91)] = 1782,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pest, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_operator, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_operator, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_tag, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_tag, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat2, 2, 0, 0), SHIFT_REPEAT(62),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat2, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat2, 2, 0, 0), SHIFT_REPEAT(30),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 4, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_push, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_peek_slice, 6, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_insensitive_string, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_operator, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat2, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__terminal, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_push_literal, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_peek_slice, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_operator, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_peek_slice, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_operator, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_operator, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pest_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pest_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pest_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pest, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pest_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pest_repeat1, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar_rule, 6, 0, 1),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grammar_rule, 6, 0, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar_rule, 5, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grammar_rule, 5, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [216] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_id, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pest(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pest",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
